### ISSUE TITLE
Tracking work on arithmetic, factoring and elliptic curves bloqs, simulation and costs

### ISSUE THREAD

**Issue by NoureldinYosri** [quantumlib/Qualtran#1337]
This is a personal issue to track factoring and elliptic curves work

- [x] https://github.com/quantumlib/Qualtran/pull/924
- [x] https://github.com/quantumlib/Qualtran/pull/1020
- [x] https://github.com/quantumlib/Qualtran/pull/1057
- [x] https://github.com/quantumlib/Qualtran/pull/1093
- [ ] https://github.com/quantumlib/Qualtran/pull/1163
- [x] https://github.com/quantumlib/Qualtran/pull/1174
- [x] https://github.com/quantumlib/Qualtran/pull/1264
- [ ] https://github.com/quantumlib/Qualtran/pull/1273
- [x] https://github.com/quantumlib/Qualtran/pull/1277
- [x] https://github.com/quantumlib/Qualtran/pull/1283
- [x] https://github.com/quantumlib/Qualtran/pull/1295
- [x] https://github.com/quantumlib/Qualtran/pull/1300
- [x] https://github.com/quantumlib/Qualtran/pull/1329
- [x] https://github.com/quantumlib/Qualtran/pull/1332
- [x] https://github.com/quantumlib/Qualtran/pull/1338
- [x] https://github.com/quantumlib/Qualtran/pull/1339
- [x] https://github.com/quantumlib/Qualtran/pull/1408
- [x] https://github.com/quantumlib/Qualtran/pull/1395
- [x] https://github.com/quantumlib/Qualtran/pull/1464
- [x] https://github.com/quantumlib/Qualtran/pull/1483
- [x] https://github.com/quantumlib/Qualtran/pull/1486
- [x] https://github.com/quantumlib/Qualtran/pull/1496
