### ISSUE TITLE
Running list of things in bloqs I want to rename

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#201]
- [x] `CompositeBloqBuilder` -> `BloqBuilder` #146 #287 
- [x] registers `wireshape` -> `shape`  #127 #288 
- [x] `FancyRegisters` -> `RegisterGroup` #142 #290 
- [x] `FancyRegister` -> `Register` or `Reg` ?
- [ ] `Bloq.decompose_bloq` -> `Bloq.decompose`
- [x] `Bloq.on_registers` -> `as_cirq_op` #207 
- [ ] `CompositeBloq.flatten` -> `flat_decompose` (or `decompose_and_flatten` (too long))
- [x] `CirqGate(Bloq)` ->  `CirqGateAsBloq` #207 
- [x] `cirq_gate` module -> `cirq_conversion` #206 
- [x] `quantum_graph.quantum_graph` submodule -> ??? idk, this contains `BloqInstance` `Soquet` and `Connection`. It makes sense to keep these classes together because a) they're not very big and b) they're the three 'opaque' types used for wiring things up. Let's track this in #281 
- [x] `quregs` as the name of Dict[str, cirq.Qid] variables -> `cirq_quregs` #207 
- [x] cirq_qubitization -> qualtran #286
