### ISSUE TITLE
Logistical issues to prepare for Qualtran Launch 

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#259]
Cirq-FT is now launched. We can move the Cirq-FT development to Cirq open source and delete all code from here to cleanup the repository. We should also start to reorganize the repo to target a Qualtran launch. 

Let's start worrying about annoying things like mypy types, pytest coverage etc. sooner than later. I had to spend 3 days and nights over the weekend fixing things for Cirq-FT launch. Let's make sure to not be in the same situation again for the Qualtran launch. 

Some subtasks to track:

- [x] Remove Cirq-FT specific code #260 
- [x] Reorganize Bloqs stuff into sub-packages if needed (eg: interop / infra / algos / vis) #296 
- [x] Rename the repository to qualtran 
- [x] Add copyright notices to all files (like Cirq?) #302 
- [ ] Improve test coverage and make coverage checks part of the CI. https://github.com/quantumlib/Qualtran/issues/305
- [x] Fix mypy typing issues and add mypy checks to CI (eg: `build_composite_bloq` method, which is core to bloqs, is not mypy safe as implemented today because the derived bloqs will not satisfy LSP. (a) Do we add a type ignore to bloq implementation -- this would be annoying? (b) Do we have all concrete implementations accept a `**soqs: 'SoquetT'` -- This would be less aesthetic? . I chose  (b) for Cirq-FT's `decompose_with_registers` but it'd be good to have some discussion here. ) #303 
- [x] Decide a dependency strategy for interop with Cirq-FT  --  Do we need to have a Cirq-style metapackage with `qualtran-core` that only has Bloqs stuff and does not depend on Cirq-FT and then have a separate `qualtran-cirq-ft` for interop with Cirq (this comes with additional overhead of setting up the meta packaging infra like in Cirq)? Or do we make Bloqs depend on Cirq-FT as a core dependency and and not worry about meta-packaging logistics for now?
